<<<<<<< HEAD
# H2 Database (??? ?????????? ? ????????????)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:shareit
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
=======
>>>>>>> 320a227ca05a1a71b99fe7832fbbde6761cf1ef4
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

<<<<<<< HEAD
# Logging
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
=======
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

# TODO Append connection to Postgres DB
#spring.datasource.driverClassName
#spring.datasource.url
#spring.datasource.username
#spring.datasource.password
>>>>>>> 320a227ca05a1a71b99fe7832fbbde6761cf1ef4
