server.port=9090
spring.application.name=shareit-server

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/shareit
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console